#!/usr/bin/env python3
"""Refresh master interview indexes from per-interview metadata."""

from __future__ import annotations

import argparse
import csv
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List

import _interview_lib as lib


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Refresh master_index.md and master_index.csv from interview metadata.",
    )
    parser.add_argument(
        "--interviews-root",
        type=Path,
        default=lib.default_interviews_root(__file__),
        help="Path to interviews root (default: parent of scripts directory).",
    )
    parser.add_argument(
        "--excel",
        type=str,
        default=None,
        help="Optional Excel tracker path override.",
    )
    parser.add_argument(
        "--no-excel-prefill",
        action="store_true",
        help="Disable metadata prefill attempts from readable Excel files.",
    )
    return parser.parse_args()


def _ensure_required_metadata(interview_dir: Path, metadata: Dict[str, object]) -> Dict[str, object]:
    basics = lib.parse_folder_basics(interview_dir.name)
    defaults = lib.metadata_defaults(
        date_str=basics.get("date", ""),
        guest_name=basics.get("guest_name", ""),
        topic=basics.get("topic", ""),
        drive_folder=interview_dir.name,
        interview_id=basics.get("interview_id", "") or None,
    )

    out = dict(metadata)
    for key, default_value in defaults.items():
        if key in lib.LIST_FIELDS:
            current = lib.ensure_list(out.get(key, []))
            out[key] = current if current else default_value
            continue
        if not lib.normalize_whitespace(out.get(key, "")):
            out[key] = default_value

    out["status"] = lib.normalize_status(out.get("status", "")) or "planned"
    out["confidentiality"] = lib.normalize_confidentiality(out.get("confidentiality", "")) or "mixed"
    out["source_files"] = lib.ensure_list(out.get("source_files", []))
    out["tags"] = lib.ensure_list(out.get("tags", []))
    out["chapter_candidates"] = lib.ensure_list(out.get("chapter_candidates", []))
    out["drive_folder"] = lib.normalize_whitespace(out.get("drive_folder", "")) or interview_dir.name
    return out


def _md_escape(value: object) -> str:
    return str(value).replace("|", "\\|").strip()


def _list_to_text(value: object) -> str:
    return "; ".join(lib.ensure_list(value))


def _row_from_metadata(interview_dir: Path, metadata: Dict[str, object]) -> Dict[str, str]:
    return {
        "interview_id": lib.normalize_whitespace(metadata.get("interview_id", "")),
        "date": lib.normalize_whitespace(metadata.get("date", "")),
        "guest_name": lib.normalize_whitespace(metadata.get("guest_name", "")),
        "guest_role": lib.normalize_whitespace(metadata.get("guest_role", "")),
        "org": lib.normalize_whitespace(metadata.get("org", "")),
        "topic": lib.normalize_whitespace(metadata.get("topic", "")),
        "platform": lib.normalize_whitespace(metadata.get("platform", "")),
        "status": lib.normalize_whitespace(metadata.get("status", "")),
        "confidentiality": lib.normalize_whitespace(metadata.get("confidentiality", "")),
        "tags": _list_to_text(metadata.get("tags", [])),
        "chapter_candidates": _list_to_text(metadata.get("chapter_candidates", [])),
        "excel_link": lib.normalize_whitespace(metadata.get("excel_link", "")),
        "drive_folder": lib.normalize_whitespace(metadata.get("drive_folder", interview_dir.name)),
        "recording_link": lib.normalize_whitespace(metadata.get("recording_link", "")),
        "source_files": _list_to_text(metadata.get("source_files", [])),
        "folder": interview_dir.name,
    }


def _write_csv(path: Path, rows: List[Dict[str, str]]) -> None:
    columns = [
        "interview_id",
        "date",
        "guest_name",
        "guest_role",
        "org",
        "topic",
        "platform",
        "status",
        "confidentiality",
        "tags",
        "chapter_candidates",
        "excel_link",
        "drive_folder",
        "recording_link",
        "source_files",
        "folder",
    ]
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=columns)
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def _write_markdown(path: Path, rows: List[Dict[str, str]]) -> None:
    now_utc = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S")
    lines = [
        "# Master Interview Index",
        "",
        "Generated by `scripts/update_index.py`.",
        "",
        f"Last updated (UTC): `{now_utc}`",
        "",
        "| Date | Guest | Topic | Status | Confidentiality | Folder | Excel |",
        "|---|---|---|---|---|---|---|",
    ]

    if not rows:
        lines.append("| - | - | - | - | - | - | - |")
    else:
        for row in rows:
            folder = row.get("folder", "")
            folder_cell = f"[{_md_escape(folder)}](./{folder})" if folder else "-"
            excel_link = row.get("excel_link", "")
            excel_cell = f"[{_md_escape(excel_link)}]({excel_link})" if excel_link else "-"
            lines.append(
                "| {date} | {guest} | {topic} | {status} | {conf} | {folder_cell} | {excel_cell} |".format(
                    date=_md_escape(row.get("date", "")),
                    guest=_md_escape(row.get("guest_name", "")),
                    topic=_md_escape(row.get("topic", "")),
                    status=_md_escape(row.get("status", "")),
                    conf=_md_escape(row.get("confidentiality", "")),
                    folder_cell=folder_cell,
                    excel_cell=excel_cell,
                )
            )

    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    args = parse_args()
    interviews_root = args.interviews_root.resolve()
    interviews_root.mkdir(parents=True, exist_ok=True)

    global_excel = lib.detect_global_excel(interviews_root, args.excel)
    interview_dirs = lib.discover_interview_dirs(interviews_root)

    rows: List[Dict[str, str]] = []
    updated_metadata_files = 0

    for interview_dir in interview_dirs:
        metadata_path = interview_dir / "_meta" / "metadata.yml"
        metadata = lib.load_metadata(metadata_path) if metadata_path.exists() else {}
        metadata = _ensure_required_metadata(interview_dir, metadata)
        changed = not metadata_path.exists()

        interview_excel = lib.detect_per_interview_excel(interview_dir)
        preferred_excel = interview_excel or global_excel
        if preferred_excel:
            excel_link = lib.relative_posix(preferred_excel, interviews_root)
            if interview_excel:
                changed = lib.set_if_different(metadata, "excel_link", excel_link) or changed
            elif not lib.normalize_whitespace(metadata.get("excel_link", "")):
                changed = lib.set_if_different(metadata, "excel_link", excel_link) or changed

        if preferred_excel and not args.no_excel_prefill:
            prefill, _message = lib.prefill_from_excel(preferred_excel, metadata)
            changed = lib.merge_missing(metadata, prefill) or changed

        if changed:
            lib.write_metadata(metadata_path, metadata)
            updated_metadata_files += 1

        rows.append(_row_from_metadata(interview_dir, metadata))

    rows.sort(key=lambda row: (row.get("date", ""), row.get("guest_name", "")), reverse=True)

    csv_path = interviews_root / "master_index.csv"
    md_path = interviews_root / "master_index.md"
    _write_csv(csv_path, rows)
    _write_markdown(md_path, rows)

    print(f"Interviews scanned: {len(interview_dirs)}")
    print(f"Metadata files updated: {updated_metadata_files}")
    print(f"Wrote: {csv_path}")
    print(f"Wrote: {md_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

