param(
  [string]$DrivePath = "G:\My Drive\The Target Trap (Book Project)",
  [string]$OutputPath = "C:\Users\Dave_\OneDrive\Desktop\Economics\projects\BOOK\GoogleDrive\INDEX.md"
)

$ErrorActionPreference = "Stop"

if (-not (Test-Path -LiteralPath $DrivePath)) {
  throw "Drive path not found: $DrivePath"
}

$items = Get-ChildItem -LiteralPath $DrivePath -Recurse -File -ErrorAction SilentlyContinue |
  Where-Object { $_.Extension -in ".gdoc", ".gsheet", ".gslides" } |
  Sort-Object FullName

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("# Google Drive Index - THE TARGET TRAP")
$lines.Add("")
$lines.Add("Last refreshed: $(Get-Date -Format 'yyyy-MM-dd')")
$lines.Add("Drive path: ``$DrivePath``")
$lines.Add("")
$lines.Add("## Google Docs found")
$lines.Add("")
$lines.Add("| Name | Type | Last modified | Path |")
$lines.Add("|---|---|---|---|")

foreach ($item in $items) {
  $type = switch ($item.Extension) {
    ".gdoc" { "Google Doc" }
    ".gsheet" { "Google Sheet" }
    ".gslides" { "Google Slides" }
    default { "Google file" }
  }

  $name = $item.Name.Replace("|", "\|")
  $path = $item.FullName.Replace("|", "\|")
  $modified = $item.LastWriteTime.ToString("yyyy-MM-dd HH:mm:ss")
  $lines.Add("| ``$name`` | $type | $modified | ``$path`` |")
}

if ($items.Count -eq 0) {
  $lines.Add("| _none found_ | - | - | - |")
}

$lines.Add("")
$lines.Add("## Notes")
$lines.Add("- Generated by ``refresh_drive_index.ps1``.")
$lines.Add("- If files are missing, confirm Google Drive Desktop is running and the folder is visible at the configured path.")

Set-Content -LiteralPath $OutputPath -Value $lines -Encoding UTF8
Write-Output "Wrote index: $OutputPath"
